// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE5G4QGSCyfwUFqXo0rWh9JKe9WPlMUGY',
    appId: '1:406075790674:web:e82bf7d2a0c332a95a568b',
    messagingSenderId: '406075790674',
    projectId: 'brandr-67309',
    authDomain: 'brandr-67309.firebaseapp.com',
    storageBucket: 'brandr-67309.firebasestorage.app',
    measurementId: 'G-FLB5LCVQPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATfcSWW8ACLrZVjfuwjtjAxZlnQ4hLF40',
    appId: '1:406075790674:android:0cb3322560a6a3a05a568b',
    messagingSenderId: '406075790674',
    projectId: 'brandr-67309',
    storageBucket: 'brandr-67309.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBbEYYY_XhnUAXjMmk3xCHlHv4AuwEiXY',
    appId: '1:406075790674:ios:db627a98a1a4d0265a568b',
    messagingSenderId: '406075790674',
    projectId: 'brandr-67309',
    storageBucket: 'brandr-67309.firebasestorage.app',
    iosBundleId: 'com.example.brandr',
  );
}
